# Generated by Django 3.2.7 on 2021-10-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(choices=[('D', 'DPI'), ('P', 'Pasaporte')], default='D', max_length=20),
        ),
    ]
