# Generated by Django 3.2.7 on 2021-10-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_cliente_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(choices=[('P', 'Pasaporte'), ('D', 'DPI')], default='D', max_length=20),
        ),
    ]
