# Generated by Django 3.2.7 on 2021-10-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cliente_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(choices=[('PASPORT', 'Pasaporte'), ('DPI', 'DPI')], default='D', max_length=20),
        ),
    ]
