# Generated by Django 3.2.8 on 2021-10-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211026_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.CharField(choices=[('08:00-09:00', '8 AM'), ('09:00-10:00', '9 AM'), ('10:00-11:00', '10 AM'), ('11:00-12:00', '11 AM'), ('12:00-13:00', '12 PM'), ('13:00-14:00', '1 PM'), ('14:00-15:00', '2 PM'), ('15:00-16:00', '3 PM'), ('16:00-17:00', '4 PM'), ('17:00-18:00', '5 PM'), ('18:00-19:00', '6 PM'), ('19:00-20:00', '7 PM'), ('20:00-21:00', '8 PM')], default='', max_length=20)),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=50)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('actualizacion', models.DateField(auto_now_add=True)),
                ('nombre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.cliente')),
            ],
        ),
    ]
