# Generated by Django 3.2.8 on 2021-10-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_reservas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
