# Generated by Django 3.2.8 on 2021-10-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_reservas_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='no_doc',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
