# Generated by Django 3.2.8 on 2021-10-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cliente_no_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
